name = "api"
version = "0.0.1"

target = "javascript"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glen = ">= 2.2.2 and < 3.0.0"
gleam_http = ">= 3.7.2 and < 4.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
conversation = ">= 2.0.1 and < 3.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"

[javascript]
typescript_declarations = true
runtime = "bun"
