name = "giolt-api"
compatibility_flags = ["nodejs_compat", "nodejs_compat_populate_process_env"]
main = "build/dev/javascript/api/index.js"
compatibility_date = "2025-05-05"

[dev]
port = 3001

[build]
command = "gleam build && bun run build.bun.ts"

[[d1_databases]]
binding = "DB"
database_name = "giolt-db"
database_id = "DB"
migrations_dir = "./drizzle"